export default [
  { colorName: 'Aqua', color: '#00BFFF' },
  { colorName: 'Black', color: '#000000' },
  { colorName: 'Brick Yellow', color: '#D9AE5E' },
  { colorName: 'Bright Blue', color: '#3B9C9C' },
  { colorName: 'Bright Bluish Green', color: '#00FC9C' },
  { colorName: 'Bright Green', color: '#00FF00' },
  { colorName: 'Bright Orange', color: '#FF6600' },
  { colorName: 'Bright Purple', color: '#DF73FF' },
  { colorName: 'Bright Red', color: '#FF0000' },
  { colorName: 'Bright Reddish Violet', color: '#8C008C' },
  { colorName: 'Bright Yellow', color: '#FFF000' },
  { colorName: 'Bright Yellowish Green', color: '#9B9B00' },
  { colorName: 'Cool Yellow', color: '#C2E093' },
  { colorName: 'Dark Azur', color: '#2E8B57' },
  { colorName: 'Dark Brown', color: '#5B3911' },
  { colorName: 'Dark Green', color: '#184632' },
  { colorName: 'Dark Orange', color: '#FF8C00' },
  { colorName: 'Dark Red', color: '#7B1E1E' },
  { colorName: 'Dark Stone Grey', color: '#4A4E4D' },
  { colorName: 'Earth Blue', color: '#1E2F3B' },
  { colorName: 'Flame Yellowish Orange', color: '#FDBE02' },
  { colorName: 'Lavender', color: '#AC79C1' },
  { colorName: 'Light Nougat', color: '#EFC297' },
  { colorName: 'Light Purple', color: '#A68BD7' },
  { colorName: 'Light Royal Blue', color: '#417DC1' },
  { colorName: 'Medium Azur', color: '#3B638C' },
  { colorName: 'Medium Blue', color: '#1C3D73' },
  { colorName: 'Medium Lavender', color: '#A57F68' },
  { colorName: 'Medium Nougat', color: '#AA7F5B' },
  { colorName: 'Medium Stone Grey', color: '#808487' },
  { colorName: 'Nougat', color: '#C58C85' },
  { colorName: 'Olive Green', color: '#B9B57D' },
  { colorName: 'Reddish Brown', color: '#582A12' },
  { colorName: 'Sand Blue', color: '#786D5F' },
  { colorName: 'Sand Yellow', color: '#DAB37D' },
  { colorName: 'Silver Metallic', color: '#A4A4A4' },
  { colorName: 'Spring Yellowish Green', color: '#ECE338' },
  { colorName: 'Vibrant Coral', color: '#FF4981' },
  { colorName: 'Vibrant Yellow', color: '#FFE600' },
  { colorName: 'Warm Gold', color: '#F6CD0A' },
  { colorName: 'White', color: '#FFFFFF' },
];